server:
  port: 12240

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  datasource:
    # 本地文件保存在项目根目录 ./data/wx_bill（会生成 wx_bill.mv.db 文件）
    #    url: jdbc:h2:file:./data/wx_bill;MODE=MySQL;DATABASE_TO_UPPER=false;AUTO_SERVER=TRUE
    #    driver-class-name: org.h2.Driver
    #    username:
    #    password:
    url: jdbc:mysql://localhost:3306/bill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    prefix: file:./ext/templates/
    suffix: .html
    cache: false
mercury:
  view:
    salt:                # 页面访问口令（路径参数），用于简单校验
