server:
  port: 8080

spring:
  datasource:
    # 本地文件保存在项目根目录 ./data/wx_bill（会生成 wx_bill.mv.db 文件）
    url: jdbc:h2:file:./data/wx_bill;MODE=MySQL;DATABASE_TO_UPPER=false;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql   # 启动时自动建表
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

# 方便本地查看
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console
